### ISSUE TITLE
Local repo todo

### ISSUE THREAD

**Issue by streamich** [jsonjoy-com/reactive-rpc#9]
- [ ] Session method tests
- [ ] Local repo method tests
- [ ] Event system tests
- [ ] Cleanup tests
- [ ] Concurrency scenarios tests
